apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  - namespace.yaml
  - prometheus-community-repo.yaml
  - loki-repo.yaml
  - kube-prometheus-stack.yaml
  - promtail-helmrelease.yaml
  - grafana-ingress.yaml
  - loki-helmrelease.yaml
  - loki_grafana_dashboard.yaml
