apiVersion: v1
kind: Secret
metadata:
    name: wordpress-salts
    namespace: blog
data:
    AUTH_KEY: ENC[AES256_GCM,data:dF/FyPvxTgXJWkc3wZhoHjtGcpsuS1ji9hLPX0vZm7jwxJkREbs+NDkDTNmOTGAax5Q/FlLgC6qx4C1hxLK9PAFz/WhOAInkiKGsnkhteAqp8l/t7YL7sg==,iv:3oI9shJLpqc5BfBhBOOKnipsh9B0u2T5yGv5f059I5k=,tag:O3IGjABki6rS4HAD/C3Fiw==,type:str]
    AUTH_SALT: ENC[AES256_GCM,data:Ka6U7cH4DTW5gO8R8LN+NfgJqrXcEzjOrlwpW4cj9/hjLEwVIvIDOjTag4GaCHciIdtvG0jd1EjYwcF2obrJeKSGcavEgatrNpTvLD/p91BkQCpEcoY5hA==,iv:EqkxgXUnjtJxVhrDVxYH4l4uarpr/jyJeGXC50q4B4g=,tag:VbEy3lPuC2wrJSiwzk1rZw==,type:str]
    LOGGED_IN_KEY: ENC[AES256_GCM,data:jKwW1yzWAcQzcSrXRN4pvQNVJhtIHYrcNSv0sWeX8p+39g3zirr2d13+jo2aLwNTGCgO33m9Tyg8ZYXFn82DTPvb5U2Fir5JjVh+/QmvlYoPqKgMdksfpQ==,iv:IG+TFgmxwck1WmAjwPduCoe2GlDido5PjMNonnS5wmY=,tag:7nOoc2bQ0fbsuLh8YIZyTQ==,type:str]
    LOGGED_IN_SALT: ENC[AES256_GCM,data:1IwCLwj+IiW8s05cdZgCZq0dgsBtYQkZsUNetK6uhUQgU5SZJsu1CEHK6EvqtFBWOHXS5PDfZY18FHgBJaL2+diNRWUM5t25tzCbyT15iZIA+m3wfOOevA==,iv:gNVdUiP+mNcBwILCbovZvluUbV5alvO8/9lMlJtwTbE=,tag:lDwmZwJl0ydVBmc02yazlw==,type:str]
    NONCE_KEY: ENC[AES256_GCM,data:9JC0/nDnea4IUTSV7JLmlNWoAtjG+baLFUPZl/Ap2wZH1TOrVMNRqSR6Hzbfh6bXxtmgaohcQ7v1Rc/LOdYkJHFD/NckvclrTYETDnthKfCx2g9itD3w4A==,iv:TXfV5QP4rAbGk8q4PUQgtzbQhy8UZUSBRqy1kmED96w=,tag:V50Ifw1cyKNwThgY8UKk2A==,type:str]
    NONCE_SALT: ENC[AES256_GCM,data:120sJDq6SsTHDwwJwg7ViSVGyNsXxXer3YRqhBFv8ft3519BKDip1wpF/XdykKF7WJIYVr/VirMHZH8pAAcd1vbGZ6ovrM7JsTsaB5aN2bbi+MsuHRnzdw==,iv:qd2CBtufbjcHR4l5pO4wpVhSkVnkUofAoh/xXmZPoXA=,tag:DzZqu/vDFccKPRmfBYCfPg==,type:str]
    SECURE_AUTH_KEY: ENC[AES256_GCM,data:JrE6aVAEArI6BoriynQ2uLP5jPCcLu2jCy8IfGLDXkzCrOIHj2yIGsK54g1Z3UflQh66xEzHlLlQaSoXPBcQG3oy2CUoSLjrJAFFGh1ZdpjcxK8hxDKJ6A==,iv:lxCQO7GSudSKP2N4D4al8SoOSvXB6D+NEOPwo64pm+Q=,tag:CusOLzdOWV4vtIuH8mIUNw==,type:str]
    SECURE_AUTH_SALT: ENC[AES256_GCM,data:Uzxn5ldl6Uta3Y0aIFeVWL8YObpbxNatMw/KfPkl7XOJ13QAsP37vsNoZTBsEKirw03Lx5Op6b0KzHtLD4xgKCCdlFbn8o8jDtdVYtAwtdSxjUCoDN1kYA==,iv:t+bY8FNGgqUvpuHXhc+luCKIyKLPULau80+Hv/aJHmA=,tag:Q+fRY62eamiE+U5ci82blw==,type:str]
sops:
    age:
        - recipient: age1rzhequ8s42qvmvuhugz5m48d45wcp0j4mt5ynvk72rkrvetw093sywft7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZ1NkZGEybkJzZVl2R2VC
            ZzFJNzlHMC9qcTZ0cmZrVmI3ZEdsVmRGQUg0CmtVVDlZYS83TXVvaTIzbUl3aWFp
            Rk91MGxIM2xXb3BscTJpR3ZnVGxmeDAKLS0tIENwQUtiNnZ0TGpPeGRUcW94OWl3
            Qkpyc01XckVPVitiSHVmVFZveklBQ1kKxq62vl/7EIjW1C/Sono+dceRuHFLUFKV
            xWDD6gDV+pSACsZe0yWkV7EU2XmvxhaaVK6sub7RTgi/lsnCJUeRKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T07:15:50Z"
    mac: ENC[AES256_GCM,data:jolFHo7kQYHRzfwBPmM072GV3Z/5LMh5kJwyr6ejmQSLBx8ODiR4o2x7wkmMSXbKISXHiRxQNHgekUuMv20bRIRXkzan7fR97kND4wPNELUp09vULxptXq5RpZj/lI1CLVaumkDLIPIjW334EVcOsR2iTU88YXYSTQ9gw1CVTRA=,iv:2f/4gXniqNJkOiEYRm+wQvYiCmWi9WcFEoMJ8C/J+GQ=,tag:pUrBmjPzrN13TVPlEkjzmQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
