apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: blog
type: Opaque
stringData:
    mysql-root-password: ENC[AES256_GCM,data:4J6g,iv:l8fKCKxIrP+PiQJ+h8hmblYbt9909B+OqkWumcet67A=,tag:w3eFR9TwEFZZdT4zGqHVDQ==,type:str]
    mysql-database: ENC[AES256_GCM,data:ryBHZrh5+H4h,iv:+xtTEns3/HA+N6SgGR9lXrvca/7mSamBBnbA+lHpNEU=,tag:LUJdTZ5XLfwNBbhEqJN5Ag==,type:str]
    mysql-user: ENC[AES256_GCM,data:OaRiKRk9OMX1,iv:/bzWQwAlYm0iBuFVmL0oUvkEHWr+ju5NAAATTmG4DJ8=,tag:uEK/1iMeSBYoj/IaEuuGMA==,type:str]
    mysql-password: ENC[AES256_GCM,data:UEejevEP2nU=,iv:L/Wx0ALduTluMTBGnjGrYHKmL1RRq8NXceCoqx/XicM=,tag:Y2jPz5MjfXY0MbqyL6nDOw==,type:str]
    mysql-backup-user: ENC[AES256_GCM,data:qIRPaTeU,iv:2LSFdIXDPcDvNwlKAFcwLsEG3BAduNHEX2fxHCmYWTw=,tag:xQvyhwER2Mo4+DdshEg9XA==,type:str]
    mysql-backup-password: ENC[AES256_GCM,data:sF62,iv:UwRuN8raJ3jlpixSHDzxUUzD19BrNJfyErMsTwxFGI0=,tag:TAr560Ihz0vR93eBbKBgVQ==,type:str]
sops:
    age:
        - recipient: age1rzhequ8s42qvmvuhugz5m48d45wcp0j4mt5ynvk72rkrvetw093sywft7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcENHdXpEaXNWbU5PWFpx
            SlQxTzlhOVZPL2diLzc3MkhXakdURExDQzI4Cmo4MFFOcVFpRXlEamxGcVQ0Nkkx
            QmlJVWNtTWhrZ3RTenlja1I1dWltTEEKLS0tIE4xNjRUNWFJekxOQzhzUnVXR1o3
            U0NoVHBsU0Z5em5XUHJGWWZlMHRlWkEKMGaECC9j8Jh2vU9w/jLi7QtxfHRAQO6+
            zGz5G5qB73Tt/mafcYyPnn3jtMYnsK7OkS3Uqhe5O+qrEvg8SpLs0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T06:12:54Z"
    mac: ENC[AES256_GCM,data:t3WwuqepMrdEMcwrWVmVXeiLXfZf1sYIbJvZ9VpCGPt5Zpyd41DJNftQaMBgc6tEwO8FxcWkSA2JSGSuxgfYN7Zbw8bth51Bj3Q9loStGedE6vMKwypGvMrBB30N4lSIahkhSomrsWYhjIu41CJfDa2PLtq/fCZb4gGigDdePEM=,iv:QrMOo2rEMFnOVwUksGyck6mr7CP8ba/YZnq+TeV4+gw=,tag:mjRuy1h5dYzQRW4GXWB3bQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
